[build]
  functions = "lambda"
  command = "env ; export ; npm run build:lambda"
  publish = "static"

[build.environment]
  MADE_UP_VARIABLE_1 = "foo"
  MADE_UP_VARIABLE_2 = "bar"


[context.branchname.environment]
  MADE_UP_VARIABLE_3 = "welp"
