[build]
  functions = "lambda"
  command = "npm run build:lambda"
  publish = "static"

[build.environment]
  MADE_UP_VARIABLE_1 = "foo"
  MADE_UP_VARIABLE_2 = "bar"

[context.new-branch.environment]
  MADE_UP_VARIABLE_3 = "welp alright"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, authorization"
      Access-Control-Allow-Origin = "https://distracted-poitras-cc447e.netlify.app/"
      Access-Control-Allow-Methods = "POST, OPTIONS"
      Access-Control-Allow-Credentials = "true"
      Vary = "Origin"

[[redirects]]
  from = "/no-country"
  to = "/blog-no-country"
  status = 302
  force = true

[[redirects]]
  from = "/country-lower"
  to = "/blog-country-lower"
  status = 302
  force = true
  country = "us"

[[redirects]]
  from = "/country-upper"
  to = "/blog-country-upper"
  status = 302
  force = true
  country = "US"

[[redirects]]
  from = "/country-upper-cond"
  to = "/blog-country-upper-cond"
  status = 302
  force = true
  conditions = { country = ["US"] }

[[redirects]]
  from = "/country-lower-cond"
  to = "/blog-country-lower-cond"
  status = 302
  force = true
  conditions = { country = ["us"] }

[[redirects]]
  from = "/country-capital-country-cond-no-array"
  to = "/blog-country-capital-country-cond-no-array"
  status = 302
  force = true
  conditions = { Country = "us" }



[[redirects]]
  from = "/*"
  to = ".netlify/functions/dns"
  status = 200

